name: Midnight Cron
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API route to prevent Planetscale sleeping
        run: |
          curl --request GET --url 'https://ddal.dekok.app/api/trpc/characters.getOne?batch=a&input=%7B%220%22%3A%7B%22json%22%3A%7B%22characterId%22%3A%22cl6ln16fq0056lce2a4xrklif%22%7D%7D%7D'
